name: Python 3.6

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Build Python 3.6
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: python/3.6
          file: python/3.6/Dockerfile
          # platforms: linux/amd64,linux/arm64
          platforms: linux/amd64
          push: true
          tags: binkhq/python:3.6
